### ISSUE TITLE
Revert to prior-to-plugin installation state

### ISSUE THREAD

**Issue by dodalovic** [dkandalov/ijkl-shortcuts-plugin#8]
Hi, I just decided to uninstall the plugin. 
How can I restore things the way they used to be before the plugin install?

Thanks

**Comment by dkandalov** [comment]
Hi Dusan,
 
Do you have any specific issues?
Everything should be back to how it was after uninstall. I haven't really checked uninstallation though 🙈 

The plugin modifies shortcuts on the fly and they should not be persisted (here is the full list of shortcuts https://github.com/dkandalov/ijkl-shortcuts-plugin/blob/master/resources/ijkl-keymap.xml).

**Comment by dodalovic** [comment]
Even after uninstalling the plugin, the new shortcuts remain.

**Comment by dkandalov** [comment]
You're right, removing additional shortcuts didn't work properly on application shutdown :( Thanks a lot for noticing and reporting the issue!

I'll release a new version of the plugin with the fix. It usually takes couple days for Jetbrains to approve, so in the meantime you can try installing plugin from this zip file https://github.com/dkandalov/ijkl-shortcuts-plugin/blob/master/ijkl-shortcuts.zip and then uninstalling it.

**Comment by dkandalov** [comment]
Although it might not actually work :( Because the old version of the plugin didn't remove shortcuts and they were persisted in keymap, the new version of the plugin will consider them to be existing shortcuts (as if they were manually added by IDE user) and won't remove them.

So maybe removing shortcuts manually is the most reliable option (this is the list of added shortcuts https://github.com/dkandalov/ijkl-shortcuts-plugin/blob/master/resources/ijkl-keymap.xml).
